blank_issues_enabled: false
contact_links:
  - name: Contact me on Discord
    url: https://discord.com/users/354191516979429376
    about: If you need help you can write to me on Discord or create an issue